// BASE COLORS
export const COLOR_PRIMARY = "#007ac7"
export const COLOR_SECONDARY = "#c40058"
export const COLOR_GRAY_DARK = "#666666"
export const SCREEN_BACKGROUND_COLOR = "#ebebeb"

// APP VIEWS COlOR
export const MAP_MARKER_COLOR = COLOR_SECONDARY
export const MARKER_ICON_COLOR = COLOR_GRAY_DARK
export const TITLE_TEXT_COLOR = "#1c1c1c"
export const SUBTITLE_TEXT_COLOR = COLOR_GRAY_DARK